# Generated by Django 5.1.3 on 2024-12-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chub_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaupload',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='media_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='upload_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
